ventilator:
  name: Ventilator-1
  connection:
    type: serial
    link: /dev/ttyACM0
    baud: 9600
    timeout: 1
  alarm:
    pin: 4
  device:
    id: 85c66b7e-c6f5-4304-a0d8-f1ecdc7f6dc5
    roles:
      ventilatorAlarmSoundMonitor: true
      ventilatorDataMonitor: false
